language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t bosinsolutions/docker-sandbox -f Dockerfile.dev .

script:
  - docker run -e CI=true domenicBosin/docker-sandbox npm run test
